/**
 * AI Avatar system.
 * 5 curated AI-generated actors for the launch library.
 * More actors unlock as the FLUX portrait pack expands.
 */

export type AvatarGender = "male" | "female" | "non-binary";
export type AvatarAge = "young" | "middle" | "senior";
export type AvatarSituation =
  | "studio" | "office" | "outdoor" | "home" | "cafe" | "gym" | "kitchen"
  | "airport" | "car" | "beach" | "snow" | "gaming" | "interview"
  | "podcast" | "green-screen" | "bathroom" | "balcony" | "nature";

export type Avatar = {
  id: string;
  name: string;
  gender: AvatarGender;
  age: AvatarAge;
  situation: AvatarSituation;
  ethnicity: string;
  thumbnailUrl: string;
  isPro: boolean;
  isHD: boolean;
  tags: string[];
  voiceId?: string;
  audioSamples?: {
    us?: string;
    uk?: string;
    ng?: string;
  };
};

// PORTRAIT_OVERRIDES_START
// Auto-generated by scripts/apply-actor-portraits.mjs — do not edit by hand.
const PORTRAIT_OVERRIDES: Record<string, string> = {
  "ava-001": "/actors/ava-001.png",
  "ava-003": "/actors/ava-003.png",
};
// PORTRAIT_OVERRIDES_END

function av(
  id: string,
  name: string,
  gender: AvatarGender,
  age: AvatarAge,
  situation: AvatarSituation,
  ethnicity: string,
  unsplashId: string,
  tags: string[],
  voiceId?: string,
): Avatar {
  const thumbnailUrl = PORTRAIT_OVERRIDES[id]
    ?? `https://images.unsplash.com/${unsplashId}?w=400&h=400&fit=crop&crop=faces`;
  return { id, name, gender, age, situation, ethnicity, thumbnailUrl, isPro: false, isHD: true, tags, voiceId };
}

export const AVATAR_LIBRARY: Avatar[] = [
  av("ava-001", "Sofia",  "female", "young",  "studio", "latina",          "photo-1531123897727-8f129e1688ce", ["beauty", "friendly", "casual"],        "EXAVITQu4vr4xnSDxMaL"),
  av("ava-003", "Emma",   "female", "young",  "cafe",   "european",        "photo-1494790108377-be9c29b29330", ["lifestyle", "food", "casual"],          "21m00Tcm4TlvDq8ikWAM"),
  av("ava-011", "Marcus", "male",   "young",  "studio", "african-american", "photo-1507003211169-0a1dd7228f2d", ["confident", "streetwear", "casual"],   "nPczCjzI2devNBz1zQrb"),
  av("ava-016", "Tunde",  "male",   "young",  "home",   "african",          "photo-1492562080023-ab3db95bfbce", ["entrepreneur", "tech", "confident"],   "ODq5zAsR6fA0C06iWqD9"),
  av("ava-006", "Priya",  "female", "young",  "gym",    "south-asian",      "photo-1520813792240-56fc4a3765a7", ["fitness", "wellness", "active"],       "pFZP5JQG7iQjIQuC4Bku"),
];

export type VoiceSettings = {
  speed: number;
  stability: number;
  similarity: number;
  styleExaggeration: number;
};

export const DEFAULT_VOICE_SETTINGS: VoiceSettings = {
  speed: 1.0,
  stability: 0.5,
  similarity: 0.5,
  styleExaggeration: 0.1,
};
