import Link from "next/link";
import { ArrowLeft, Shield, Database, Brain, Share2, Clock, UserCheck, Lock, Baby, Globe, RefreshCw, Mail } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Famousli",
  description: "Learn how Famousli collects, uses, and protects your personal information.",
};

const sections = [
  {
    icon: Database,
    title: "1. Information We Collect",
    content: [
      {
        subtitle: "Account Information",
        text: "When you create an account, we collect your name, email address, company name, and profile picture. If you sign up via Google or GitHub OAuth, we receive your basic profile information from those providers.",
      },
      {
        subtitle: "Usage Data",
        text: "We automatically collect information about how you interact with our platform, including pages visited, features used, ads created, scheduling activity, and performance metrics. This includes your IP address, browser type, device information, and referring URLs.",
      },
      {
        subtitle: "Payment Information",
        text: "When you subscribe to a paid plan or purchase credit packs, payment processing is handled by Stripe. We do not store your full credit card number. We retain transaction IDs, billing addresses, and subscription status for our records.",
      },
      {
        subtitle: "Cookies & Tracking",
        text: "We use essential cookies for authentication and session management, analytics cookies (Google Analytics) to understand usage patterns, and marketing cookies (Meta Pixel) to measure ad campaign effectiveness. See our Cookie Policy for full details.",
      },
      {
        subtitle: "User Content",
        text: "We store the ads you create, including text copy, uploaded images, generated images, video assets, brand kits, and scheduling configurations. This content is necessary to provide our services.",
      },
    ],
  },
  {
    icon: Brain,
    title: "2. How We Use Your Information",
    content: [
      {
        subtitle: "Service Delivery",
        text: "We use your information to provide, maintain, and improve our ad creation, scheduling, and auto-posting services. This includes generating AI-powered ad copy, images, and videos based on your inputs.",
      },
      {
        subtitle: "Communication",
        text: "We may send you transactional emails (account verification, billing receipts, scheduled post confirmations), product updates, and promotional offers. You can opt out of non-essential communications at any time.",
      },
      {
        subtitle: "Analytics & Improvement",
        text: "We analyze aggregated, anonymized usage data to improve our AI models, optimize platform performance, and develop new features. Individual user data is never used to train our AI models without explicit consent.",
      },
      {
        subtitle: "Legal Compliance",
        text: "We may process your data to comply with legal obligations, respond to lawful requests from authorities, and enforce our Terms of Service.",
      },
    ],
  },
  {
    icon: Brain,
    title: "3. AI and Data Processing",
    content: [
      {
        subtitle: "How AI Processes Your Content",
        text: "When you create ads, your business description and creative preferences are sent to our AI providers (including Anthropic's Claude and Stability AI) to generate ad copy, images, and video content. These providers process your data solely to fulfill your request and do not retain it for their own training purposes.",
      },
      {
        subtitle: "AI-Generated Content",
        text: "Content generated by our AI models is created specifically for you. While AI outputs may occasionally resemble content created for other users due to the nature of generative models, you retain full ownership of your generated ads as outlined in our Terms of Service.",
      },
      {
        subtitle: "Data Minimization",
        text: "We send only the minimum necessary information to AI providers. Your payment details, account credentials, and analytics data are never shared with AI processing services.",
      },
    ],
  },
  {
    icon: Share2,
    title: "4. Data Sharing",
    content: [
      {
        subtitle: "Payment Processors",
        text: "Stripe processes all payments. They receive your billing information as needed to complete transactions. Stripe's privacy policy governs their handling of your data.",
      },
      {
        subtitle: "Social Media Platforms",
        text: "When you connect social accounts for auto-posting, we share your ad content with the platforms you select (Instagram, Facebook, TikTok, LinkedIn, X, WhatsApp, etc.). Each platform's privacy policy governs their handling of posted content.",
      },
      {
        subtitle: "AI Providers",
        text: "Anthropic (Claude) and Stability AI receive your creative inputs to generate content. These providers are contractually bound to process data only for service delivery.",
      },
      {
        subtitle: "Analytics Partners",
        text: "Google Analytics and similar services receive anonymized usage data. We do not share personally identifiable information with analytics partners.",
      },
      {
        subtitle: "No Data Sales",
        text: "We do not sell, rent, or trade your personal information to third parties for their marketing purposes. Ever.",
      },
    ],
  },
  {
    icon: Clock,
    title: "5. Data Retention",
    content: [
      {
        subtitle: "Active Accounts",
        text: "We retain your data for as long as your account is active. Your created ads, brand kits, and scheduling history remain available in your account indefinitely.",
      },
      {
        subtitle: "Deleted Accounts",
        text: "Upon account deletion, we remove your personal data within 30 days. Anonymized, aggregated analytics data may be retained indefinitely. Backup copies are purged within 90 days.",
      },
      {
        subtitle: "Legal Requirements",
        text: "We may retain certain data longer if required by law (e.g., billing records for tax compliance, typically 7 years).",
      },
    ],
  },
  {
    icon: UserCheck,
    title: "6. Your Rights",
    content: [
      {
        subtitle: "GDPR Rights (EEA Residents)",
        text: "You have the right to access, rectify, erase, restrict processing, data portability, and object to processing of your personal data. You may also withdraw consent at any time. To exercise these rights, contact support@famousli.com.",
      },
      {
        subtitle: "CCPA Rights (California Residents)",
        text: "You have the right to know what personal information we collect, request deletion, opt out of data sales (we don't sell data), and not be discriminated against for exercising your rights. Submit requests to support@famousli.com.",
      },
      {
        subtitle: "Universal Rights",
        text: "All users, regardless of location, can access their data, request corrections, download their content, and delete their accounts through our Settings page or by contacting support.",
      },
    ],
  },
  {
    icon: Lock,
    title: "7. Security Measures",
    content: [
      {
        subtitle: "Encryption",
        text: "All data is encrypted in transit (TLS 1.3) and at rest (AES-256). API keys and OAuth tokens are encrypted with additional application-layer encryption.",
      },
      {
        subtitle: "Infrastructure",
        text: "Our platform is hosted on enterprise-grade cloud infrastructure with SOC 2 compliance. We conduct regular security audits and penetration testing.",
      },
      {
        subtitle: "Access Controls",
        text: "Employee access to user data is strictly limited on a need-to-know basis. All access is logged and audited. We use multi-factor authentication for all internal systems.",
      },
    ],
  },
  {
    icon: Baby,
    title: "8. Children's Privacy",
    content: [
      {
        subtitle: "Age Requirement",
        text: "Famousli is not intended for use by individuals under 16 years of age. We do not knowingly collect personal information from children. If we discover that a child under 16 has created an account, we will promptly delete it and all associated data.",
      },
    ],
  },
  {
    icon: Globe,
    title: "9. International Data Transfers",
    content: [
      {
        subtitle: "Data Location",
        text: "Our primary servers are located in the United States. If you are accessing our services from outside the US, your data will be transferred to and processed in the US.",
      },
      {
        subtitle: "Transfer Safeguards",
        text: "For transfers from the EEA, UK, and Switzerland, we rely on Standard Contractual Clauses (SCCs) approved by the European Commission. We ensure all sub-processors maintain equivalent data protection standards.",
      },
    ],
  },
  {
    icon: RefreshCw,
    title: "10. Changes to This Policy",
    content: [
      {
        subtitle: "Notification",
        text: "We may update this Privacy Policy from time to time. We will notify you of material changes by email and/or a prominent notice on our platform at least 30 days before changes take effect. Continued use of our services after changes constitutes acceptance of the updated policy.",
      },
    ],
  },
  {
    icon: Mail,
    title: "11. Contact Us",
    content: [
      {
        subtitle: "Questions or Requests",
        text: "If you have any questions about this Privacy Policy or wish to exercise your data rights, please contact us at support@famousli.com. We aim to respond to all requests within 30 days.",
      },
    ],
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-bg-secondary/30">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 py-12 sm:py-20">
        {/* Back link */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm font-medium text-text-secondary hover:text-primary transition-colors mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to home
        </Link>

        {/* Header */}
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-4 py-1.5 text-xs font-semibold uppercase tracking-wider text-primary mb-4">
            <Shield className="h-3.5 w-3.5" />
            Privacy Policy
          </div>
          <h1 className="font-heading text-3xl sm:text-4xl md:text-5xl font-extrabold text-text-primary mb-4">
            Privacy Policy
          </h1>
          <p className="text-text-secondary text-lg">
            Last updated: April 7, 2026
          </p>
          <p className="mt-4 text-text-secondary leading-relaxed max-w-2xl">
            At Famousli, we take your privacy seriously. This policy explains how we collect,
            use, store, and protect your personal information when you use our AI-powered
            ad creation platform.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map((section) => (
            <div
              key={section.title}
              className="rounded-2xl border border-black/5 bg-white p-6 sm:p-8 shadow-sm"
            >
              <div className="flex items-center gap-3 mb-6">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10">
                  <section.icon className="h-5 w-5 text-primary" />
                </div>
                <h2 className="font-heading text-xl sm:text-2xl font-bold text-text-primary">
                  {section.title}
                </h2>
              </div>
              <div className="space-y-5">
                {section.content.map((item) => (
                  <div key={item.subtitle}>
                    <h3 className="font-heading font-semibold text-text-primary mb-1">
                      {item.subtitle}
                    </h3>
                    <p className="text-text-secondary leading-relaxed text-sm sm:text-base">
                      {item.text}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Footer note */}
        <div className="mt-12 rounded-2xl border border-black/5 bg-white p-6 sm:p-8 shadow-sm text-center">
          <p className="text-text-secondary text-sm">
            If you have questions about this privacy policy, contact us at{" "}
            <a href="mailto:support@famousli.com" className="text-primary font-semibold hover:underline">
              support@famousli.com
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
